---
- hosts: localhost
  gather_facts: no
  remote_user: simrath
  become: false
  tasks:
    - name: Create Kubernetes Namespace
      command: kubectl create namespace devops-keyphrase-extraction
      ignore_errors: yes

    - name: Apply Kubernetes Deployment
      command: kubectl apply -f /app/k8s-deployment.yml -n devops-keyphrase-extraction

    - name: Apply Kubernetes Service
      command: kubectl apply -f /app/k8s-service.yml -n devops-keyphrase-extraction
