---
- hosts: localhost
  gather_facts: no
  remote_user: simrath
  become: false
  tasks:

    - name: Set kubectl context to Minikube
      command: minikube kubectl -- get pods
      ignore_errors: yes

    - name: Apply Kubernetes Deployment
      command: kubectl apply -f k8s-deployment.yml -n devops-keyphrase-extraction

    - name: Apply Kubernetes Service
      command: kubectl apply -f k8s-service.yml -n devops-keyphrase-extraction
