# deploy_app.yml
---
- hosts: localhost
  become: true
  tasks:
    - name: Ensure kubectl is installed
      apt:
        name: kubectl
        state: present
        update_cache: yes

    - name: Create Kubernetes Namespace
      command: kubectl create namespace devops-keyphrase-extraction
      ignore_errors: yes

    - name: Apply Kubernetes Deployment
      command: kubectl apply -f /path/to/k8s-deployment.yml -n devops-keyphrase-extraction

    - name: Apply Kubernetes Service
      command: kubectl apply -f /path/to/k8s-service.yml -n devops-keyphrase-extraction
