# k8s-service.yml
apiVersion: v1
kind: Service
metadata:
  name: keyphrase-extraction-service
  namespace: devops-keyphrase-extraction
spec:
  selector:
    app: keyphrase-extraction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5551
  type: LoadBalancer
